
name: Build and deploy GH Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack
      # Use workspace target directory for cargo install's build,
      # so that the build of wasm-pack will be cached by rust-cache action.
        run: CARGO_TARGET_DIR=`pwd`/target cargo install wasm-pack

      - name: NPM install (latest)
        run: cd www && npm install npm@latest

      - name: NPM (including WASM) Build
        run: cd www && npm run build
      
      - name: Save wasm dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: www/dist
          if-no-files-found: error
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          repo: emptyfridge/game-of-life
          target_branch: gh-pages
          build_dir: build
          keep_history: false
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.token}}
